# ruff: noqa: E501  (upstream message wording sets the line length, not us)
"""Error codes extracted from the Go implementation. DO NOT EDIT BY HAND.

Regenerate with ``python server/scripts/extract_error_codes.py``. The Go sources
(pkg/models/error.go, pkg/user/error.go) are the source of truth.

Keys are "<source>.<GoErrorType>", e.g. "models.ErrProjectDoesNotExist". Neither
the code value nor the constant name is unique upstream:

* codes 1022, 1025 and 1026 are each shared by two errors in pkg/user/error.go;
* code 6002 is shared by ErrTeamDoesNotExist and ErrExternalTeamDoesNotExist
  (pkg/models/error.go declares ErrCodeOIDCTeamDoesNotExist = 6008 but never
  returns it — copied as-is, we return 6002 like the Go version does);
* the type name ErrInvalidTimezone exists in both files with different codes
  (models 2003, user 1025).

Keying by anything less specific would silently drop errors.
"""

from __future__ import annotations

from dataclasses import dataclass


class AmbiguousErrorCodeError(LookupError):
    """Raised when a numeric code maps to more than one error."""


@dataclass(frozen=True)
class ErrorCodeSpec:
    name: str
    """Table key: "<source>.<GoErrorType>"."""

    const: str
    """Go constant name, e.g. ErrCodeProjectDoesNotExist."""

    error: str
    """Go error type, e.g. ErrProjectDoesNotExist."""

    code: int
    """The `code` field of the JSON error body."""

    http_status: int

    message: str
    """str.format template; placeholders are named after the Go struct fields."""

    template_fields: tuple[str, ...]

    i18n_params: tuple[tuple[str, str], ...]
    """(client placeholder name, template field) pairs feeding `i18n_params`."""

    source: str
    """Which Go file it came from: "models" or "user"."""


ERROR_CODES: dict[str, ErrorCodeSpec] = {
    "models.ErrGenericForbidden": ErrorCodeSpec(
        name="models.ErrGenericForbidden",
        const="ErrorCodeGenericForbidden",
        error="ErrGenericForbidden",
        code=1,
        http_status=403,
        message="You're not allowed to do this.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrIDCannotBeZero": ErrorCodeSpec(
        name="models.ErrIDCannotBeZero",
        const="ErrCodeIDCannotBeZero",
        error="ErrIDCannotBeZero",
        code=2001,
        http_status=400,
        message="The ID cannot be empty or 0.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrInvalidData": ErrorCodeSpec(
        name="models.ErrInvalidData",
        const="ErrCodeInvalidData",
        error="ErrInvalidData",
        code=2002,
        http_status=400,
        message="{message}",
        template_fields=("message",),
        i18n_params=(),
        source="models",
    ),
    "models.ErrInvalidTimezone": ErrorCodeSpec(
        name="models.ErrInvalidTimezone",
        const="ErrCodeInvalidTimezone",
        error="ErrInvalidTimezone",
        code=2003,
        http_status=400,
        message="The timezone '{name}' is invalid",
        template_fields=("name",),
        i18n_params=(("timezone", "name"),),
        source="models",
    ),
    "models.ErrInvalidModel": ErrorCodeSpec(
        name="models.ErrInvalidModel",
        const="ErrCodeInvalidModel",
        error="ErrInvalidModel",
        code=2004,
        http_status=400,
        message="{message}",
        template_fields=("message",),
        i18n_params=(),
        source="models",
    ),
    "models.ErrProjectDoesNotExist": ErrorCodeSpec(
        name="models.ErrProjectDoesNotExist",
        const="ErrCodeProjectDoesNotExist",
        error="ErrProjectDoesNotExist",
        code=3001,
        http_status=404,
        message="This project does not exist.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrNeedToHaveProjectReadAccess": ErrorCodeSpec(
        name="models.ErrNeedToHaveProjectReadAccess",
        const="ErrCodeNeedToHaveProjectReadAccess",
        error="ErrNeedToHaveProjectReadAccess",
        code=3004,
        http_status=403,
        message="You need to have read access to this project.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrProjectTitleCannotBeEmpty": ErrorCodeSpec(
        name="models.ErrProjectTitleCannotBeEmpty",
        const="ErrCodeProjectTitleCannotBeEmpty",
        error="ErrProjectTitleCannotBeEmpty",
        code=3005,
        http_status=400,
        message="You must provide at least a project title.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrProjectShareDoesNotExist": ErrorCodeSpec(
        name="models.ErrProjectShareDoesNotExist",
        const="ErrCodeProjectShareDoesNotExist",
        error="ErrProjectShareDoesNotExist",
        code=3006,
        http_status=404,
        message="The project share does not exist.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrProjectIdentifierIsNotUnique": ErrorCodeSpec(
        name="models.ErrProjectIdentifierIsNotUnique",
        const="ErrCodeProjectIdentifierIsNotUnique",
        error="ErrProjectIdentifierIsNotUnique",
        code=3007,
        http_status=400,
        message="A project with this identifier already exists.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrProjectIsArchived": ErrorCodeSpec(
        name="models.ErrProjectIsArchived",
        const="ErrCodeProjectIsArchived",
        error="ErrProjectIsArchived",
        code=3008,
        http_status=412,
        message="This project is archived. Editing or creating new tasks is not possible.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrProjectCannotBelongToAPseudoParentProject": ErrorCodeSpec(
        name="models.ErrProjectCannotBelongToAPseudoParentProject",
        const="ErrCodeProjectCannotBelongToAPseudoParentProject",
        error="ErrProjectCannotBelongToAPseudoParentProject",
        code=3009,
        http_status=412,
        message="This project cannot belong a dynamically generated project.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrProjectCannotBeChildOfItself": ErrorCodeSpec(
        name="models.ErrProjectCannotBeChildOfItself",
        const="ErrCodeProjectCannotBeChildOfItself",
        error="ErrProjectCannotBeChildOfItself",
        code=3010,
        http_status=412,
        message="This project cannot be a child of itself.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrProjectCannotHaveACyclicRelationship": ErrorCodeSpec(
        name="models.ErrProjectCannotHaveACyclicRelationship",
        const="ErrCodeProjectCannotHaveACyclicRelationship",
        error="ErrProjectCannotHaveACyclicRelationship",
        code=3011,
        http_status=412,
        message="This project cannot have a cyclic relationship to a parent project.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrCannotDeleteDefaultProject": ErrorCodeSpec(
        name="models.ErrCannotDeleteDefaultProject",
        const="ErrCodeCannotDeleteDefaultProject",
        error="ErrCannotDeleteDefaultProject",
        code=3012,
        http_status=412,
        message="This project cannot be deleted because it is the default project of a user.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrCannotArchiveDefaultProject": ErrorCodeSpec(
        name="models.ErrCannotArchiveDefaultProject",
        const="ErrCodeCannotArchiveDefaultProject",
        error="ErrCannotArchiveDefaultProject",
        code=3013,
        http_status=412,
        message="This project cannot be archived because it is the default project of a user.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrProjectViewDoesNotExist": ErrorCodeSpec(
        name="models.ErrProjectViewDoesNotExist",
        const="ErrCodeProjectViewDoesNotExist",
        error="ErrProjectViewDoesNotExist",
        code=3014,
        http_status=404,
        message="This project view does not exist.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrProjectHasNoBackground": ErrorCodeSpec(
        name="models.ErrProjectHasNoBackground",
        const="ErrCodeProjectHasNoBackground",
        error="ErrProjectHasNoBackground",
        code=3015,
        http_status=404,
        message="Project background not found",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrTaskCannotBeEmpty": ErrorCodeSpec(
        name="models.ErrTaskCannotBeEmpty",
        const="ErrCodeTaskCannotBeEmpty",
        error="ErrTaskCannotBeEmpty",
        code=4001,
        http_status=400,
        message="You must provide at least a task title.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrInvalidTaskRepeatInterval": ErrorCodeSpec(
        name="models.ErrInvalidTaskRepeatInterval",
        const="ErrCodeInvalidTaskRepeatInterval",
        error="ErrInvalidTaskRepeatInterval",
        code=4029,
        http_status=400,
        message="The task repeat interval must be between 0 and {max_task_repeat_after_seconds} seconds (10 years).",
        template_fields=("max_task_repeat_after_seconds",),
        i18n_params=(),
        source="models",
    ),
    "models.ErrInvalidBulkTaskCreationCount": ErrorCodeSpec(
        name="models.ErrInvalidBulkTaskCreationCount",
        const="ErrCodeInvalidBulkTaskCreationCount",
        error="ErrInvalidBulkTaskCreationCount",
        code=4030,
        http_status=400,
        message="A bulk task creation must contain between 1 and {max_tasks_per_bulk_creation} tasks, got {count}.",
        template_fields=("max_tasks_per_bulk_creation", "count"),
        i18n_params=(),
        source="models",
    ),
    "models.ErrInvalidTaskInBulkCreation": ErrorCodeSpec(
        name="models.ErrInvalidTaskInBulkCreation",
        const="ErrCodeInvalidTaskInBulkCreation",
        error="ErrInvalidTaskInBulkCreation",
        code=4031,
        http_status=400,
        message="The task at index {index} is invalid: {message}",
        template_fields=("index", "message"),
        i18n_params=(),
        source="models",
    ),
    "models.ErrTaskDoesNotExist": ErrorCodeSpec(
        name="models.ErrTaskDoesNotExist",
        const="ErrCodeTaskDoesNotExist",
        error="ErrTaskDoesNotExist",
        code=4002,
        http_status=404,
        message="This task does not exist",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrNotificationDoesNotExist": ErrorCodeSpec(
        name="models.ErrNotificationDoesNotExist",
        const="ErrCodeNotificationDoesNotExist",
        error="ErrNotificationDoesNotExist",
        code=1003,
        http_status=404,
        message="The notification does not exist.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrBulkTasksMustBeInSameProject": ErrorCodeSpec(
        name="models.ErrBulkTasksMustBeInSameProject",
        const="ErrCodeBulkTasksMustBeInSameProject",
        error="ErrBulkTasksMustBeInSameProject",
        code=4003,
        http_status=400,
        message="All tasks must be in the same project.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrBulkTasksNeedAtLeastOne": ErrorCodeSpec(
        name="models.ErrBulkTasksNeedAtLeastOne",
        const="ErrCodeBulkTasksNeedAtLeastOne",
        error="ErrBulkTasksNeedAtLeastOne",
        code=4004,
        http_status=400,
        message="Need at least one tasks to do bulk editing.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrNoPermissionToSeeTask": ErrorCodeSpec(
        name="models.ErrNoPermissionToSeeTask",
        const="ErrCodeNoRightToSeeTask",
        error="ErrNoPermissionToSeeTask",
        code=4005,
        http_status=403,
        message="You don't have the permission to see this task.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrParentTaskCannotBeTheSame": ErrorCodeSpec(
        name="models.ErrParentTaskCannotBeTheSame",
        const="ErrCodeParentTaskCannotBeTheSame",
        error="ErrParentTaskCannotBeTheSame",
        code=4006,
        http_status=403,
        message="You cannot set a parent task to the task itself.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrInvalidRelationKind": ErrorCodeSpec(
        name="models.ErrInvalidRelationKind",
        const="ErrCodeInvalidRelationKind",
        error="ErrInvalidRelationKind",
        code=4007,
        http_status=400,
        message="The task relation is invalid.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrRelationAlreadyExists": ErrorCodeSpec(
        name="models.ErrRelationAlreadyExists",
        const="ErrCodeRelationAlreadyExists",
        error="ErrRelationAlreadyExists",
        code=4008,
        http_status=409,
        message="The task relation already exists.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrRelationDoesNotExist": ErrorCodeSpec(
        name="models.ErrRelationDoesNotExist",
        const="ErrCodeRelationDoesNotExist",
        error="ErrRelationDoesNotExist",
        code=4009,
        http_status=404,
        message="The task relation does not exist.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrRelationTasksCannotBeTheSame": ErrorCodeSpec(
        name="models.ErrRelationTasksCannotBeTheSame",
        const="ErrCodeRelationTasksCannotBeTheSame",
        error="ErrRelationTasksCannotBeTheSame",
        code=4010,
        http_status=400,
        message="You cannot relate a task with itself",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrTaskAttachmentDoesNotExist": ErrorCodeSpec(
        name="models.ErrTaskAttachmentDoesNotExist",
        const="ErrCodeTaskAttachmentDoesNotExist",
        error="ErrTaskAttachmentDoesNotExist",
        code=4011,
        http_status=404,
        message="This task attachment does not exist.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrTaskAttachmentIsTooLarge": ErrorCodeSpec(
        name="models.ErrTaskAttachmentIsTooLarge",
        const="ErrCodeTaskAttachmentIsTooLarge",
        error="ErrTaskAttachmentIsTooLarge",
        code=4012,
        http_status=400,
        message="The task attachment exceeds the configured file size of {files_max_size} bytes, filesize was {size}",
        template_fields=("files_max_size", "size"),
        i18n_params=(),
        source="models",
    ),
    "models.ErrInvalidSortParam": ErrorCodeSpec(
        name="models.ErrInvalidSortParam",
        const="ErrCodeInvalidSortParam",
        error="ErrInvalidSortParam",
        code=4013,
        http_status=400,
        message="The task sort param '{sort_by}' is invalid.",
        template_fields=("sort_by",),
        i18n_params=(),
        source="models",
    ),
    "models.ErrInvalidSortOrder": ErrorCodeSpec(
        name="models.ErrInvalidSortOrder",
        const="ErrCodeInvalidSortOrder",
        error="ErrInvalidSortOrder",
        code=4014,
        http_status=400,
        message="The task sort order '{order_by}' is invalid. Allowed is either asc or desc.",
        template_fields=("order_by",),
        i18n_params=(),
        source="models",
    ),
    "models.ErrTaskCommentDoesNotExist": ErrorCodeSpec(
        name="models.ErrTaskCommentDoesNotExist",
        const="ErrCodeTaskCommentDoesNotExist",
        error="ErrTaskCommentDoesNotExist",
        code=4015,
        http_status=404,
        message="This task comment does not exist",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrInvalidTaskField": ErrorCodeSpec(
        name="models.ErrInvalidTaskField",
        const="ErrCodeInvalidTaskField",
        error="ErrInvalidTaskField",
        code=4016,
        http_status=400,
        message="The task field '{task_field}' is invalid.",
        template_fields=("task_field",),
        i18n_params=(),
        source="models",
    ),
    "models.ErrInvalidTaskFilterComparator": ErrorCodeSpec(
        name="models.ErrInvalidTaskFilterComparator",
        const="ErrCodeInvalidTaskFilterComparator",
        error="ErrInvalidTaskFilterComparator",
        code=4017,
        http_status=400,
        message="The task filter comparator '{comparator}' is invalid.",
        template_fields=("comparator",),
        i18n_params=(),
        source="models",
    ),
    "models.ErrInvalidTaskFilterConcatinator": ErrorCodeSpec(
        name="models.ErrInvalidTaskFilterConcatinator",
        const="ErrCodeInvalidTaskFilterConcatinator",
        error="ErrInvalidTaskFilterConcatinator",
        code=4018,
        http_status=400,
        message="The task filter concatinator '{concatinator}' is invalid.",
        template_fields=("concatinator",),
        i18n_params=(),
        source="models",
    ),
    "models.ErrInvalidTaskFilterValue": ErrorCodeSpec(
        name="models.ErrInvalidTaskFilterValue",
        const="ErrCodeInvalidTaskFilterValue",
        error="ErrInvalidTaskFilterValue",
        code=4019,
        http_status=400,
        message="The task filter value '{value}' for field '{field}' is invalid.",
        template_fields=("value", "field"),
        i18n_params=(),
        source="models",
    ),
    "models.ErrAttachmentDoesNotBelongToTask": ErrorCodeSpec(
        name="models.ErrAttachmentDoesNotBelongToTask",
        const="ErrCodeAttachmentDoesNotBelongToTask",
        error="ErrAttachmentDoesNotBelongToTask",
        code=4020,
        http_status=400,
        message="This attachment does not belong to that task.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrUserAlreadyAssigned": ErrorCodeSpec(
        name="models.ErrUserAlreadyAssigned",
        const="ErrCodeUserAlreadyAssigned",
        error="ErrUserAlreadyAssigned",
        code=4021,
        http_status=400,
        message="This user is already assigned to that task.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrReminderRelativeToMissing": ErrorCodeSpec(
        name="models.ErrReminderRelativeToMissing",
        const="ErrCodeReminderRelativeToMissing",
        error="ErrReminderRelativeToMissing",
        code=4022,
        http_status=400,
        message="Please provide what the reminder date is relative to",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrTaskRelationCycle": ErrorCodeSpec(
        name="models.ErrTaskRelationCycle",
        const="ErrCodeTaskRelationCycle",
        error="ErrTaskRelationCycle",
        code=4023,
        http_status=409,
        message="This task relation would create a cycle.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrInvalidFilterExpression": ErrorCodeSpec(
        name="models.ErrInvalidFilterExpression",
        const="ErrCodeInvalidFilterExpression",
        error="ErrInvalidFilterExpression",
        code=4024,
        http_status=400,
        message="The filter expression '{expression}' is invalid: {expression_error}",
        template_fields=("expression", "expression_error"),
        i18n_params=(),
        source="models",
    ),
    "models.ErrInvalidReactionEntityKind": ErrorCodeSpec(
        name="models.ErrInvalidReactionEntityKind",
        const="ErrCodeInvalidReactionEntityKind",
        error="ErrInvalidReactionEntityKind",
        code=4025,
        http_status=400,
        message="The reaction kind '{kind}' is invalid.",
        template_fields=("kind",),
        i18n_params=(),
        source="models",
    ),
    "models.ErrMustHaveProjectViewToSortByPosition": ErrorCodeSpec(
        name="models.ErrMustHaveProjectViewToSortByPosition",
        const="ErrCodeMustHaveProjectViewToSortByPosition",
        error="ErrMustHaveProjectViewToSortByPosition",
        code=4026,
        http_status=400,
        message="You must provide a project view ID when sorting by position",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrInvalidTaskColumn": ErrorCodeSpec(
        name="models.ErrInvalidTaskColumn",
        const="ErrCodeInvalidTaskColumn",
        error="ErrInvalidTaskColumn",
        code=4027,
        http_status=400,
        message="The task field '{column}' is invalid.",
        template_fields=("column",),
        i18n_params=(),
        source="models",
    ),
    "models.ErrNeedsFullRecalculation": ErrorCodeSpec(
        name="models.ErrNeedsFullRecalculation",
        const="ErrCodeNeedsFullRecalculation",
        error="ErrNeedsFullRecalculation",
        code=4028,
        http_status=500,
        message="Position repair requires full view recalculation.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrTeamNameCannotBeEmpty": ErrorCodeSpec(
        name="models.ErrTeamNameCannotBeEmpty",
        const="ErrCodeTeamNameCannotBeEmpty",
        error="ErrTeamNameCannotBeEmpty",
        code=6001,
        http_status=400,
        message="The team name cannot be empty",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrTeamDoesNotExist": ErrorCodeSpec(
        name="models.ErrTeamDoesNotExist",
        const="ErrCodeTeamDoesNotExist",
        error="ErrTeamDoesNotExist",
        code=6002,
        http_status=404,
        message="This team does not exist.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrTeamAlreadyHasAccess": ErrorCodeSpec(
        name="models.ErrTeamAlreadyHasAccess",
        const="ErrCodeTeamAlreadyHasAccess",
        error="ErrTeamAlreadyHasAccess",
        code=6004,
        http_status=409,
        message="This team already has access.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrUserIsMemberOfTeam": ErrorCodeSpec(
        name="models.ErrUserIsMemberOfTeam",
        const="ErrCodeUserIsMemberOfTeam",
        error="ErrUserIsMemberOfTeam",
        code=6005,
        http_status=409,
        message="This user is already a member of that team.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrCannotDeleteLastTeamMember": ErrorCodeSpec(
        name="models.ErrCannotDeleteLastTeamMember",
        const="ErrCodeCannotDeleteLastTeamMember",
        error="ErrCannotDeleteLastTeamMember",
        code=6006,
        http_status=400,
        message="You cannot delete the last member of a team.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrTeamDoesNotHaveAccessToProject": ErrorCodeSpec(
        name="models.ErrTeamDoesNotHaveAccessToProject",
        const="ErrCodeTeamDoesNotHaveAccessToProject",
        error="ErrTeamDoesNotHaveAccessToProject",
        code=6007,
        http_status=403,
        message="This team does not have access to the project.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrExternalTeamDoesNotExist": ErrorCodeSpec(
        name="models.ErrExternalTeamDoesNotExist",
        const="ErrCodeTeamDoesNotExist",
        error="ErrExternalTeamDoesNotExist",
        code=6002,
        http_status=404,
        message="No team could be found for the given OIDC ID and issuer.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrOIDCTeamsDoNotExistForUser": ErrorCodeSpec(
        name="models.ErrOIDCTeamsDoNotExistForUser",
        const="ErrCodeOIDCTeamsDoNotExistForUser",
        error="ErrOIDCTeamsDoNotExistForUser",
        code=6009,
        http_status=404,
        message="No Teams with property oidcId could be found for User.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrCannotRemoveUserFromExternalTeam": ErrorCodeSpec(
        name="models.ErrCannotRemoveUserFromExternalTeam",
        const="ErrCodeCannotLeaveExternalTeam",
        error="ErrCannotRemoveUserFromExternalTeam",
        code=6010,
        http_status=412,
        message="Users cannot be removed from an external team.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrUserAlreadyHasAccess": ErrorCodeSpec(
        name="models.ErrUserAlreadyHasAccess",
        const="ErrCodeUserAlreadyHasAccess",
        error="ErrUserAlreadyHasAccess",
        code=7002,
        http_status=409,
        message="This user already has access to this project.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrUserDoesNotHaveAccessToProject": ErrorCodeSpec(
        name="models.ErrUserDoesNotHaveAccessToProject",
        const="ErrCodeUserDoesNotHaveAccessToProject",
        error="ErrUserDoesNotHaveAccessToProject",
        code=7003,
        http_status=403,
        message="This user does not have access to the project.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrLabelIsAlreadyOnTask": ErrorCodeSpec(
        name="models.ErrLabelIsAlreadyOnTask",
        const="ErrCodeLabelIsAlreadyOnTask",
        error="ErrLabelIsAlreadyOnTask",
        code=8001,
        http_status=400,
        message="This label already exists on the task.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrLabelDoesNotExist": ErrorCodeSpec(
        name="models.ErrLabelDoesNotExist",
        const="ErrCodeLabelDoesNotExist",
        error="ErrLabelDoesNotExist",
        code=8002,
        http_status=404,
        message="This label does not exist.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrUserHasNoAccessToLabel": ErrorCodeSpec(
        name="models.ErrUserHasNoAccessToLabel",
        const="ErrCodeUserHasNoAccessToLabel",
        error="ErrUserHasNoAccessToLabel",
        code=8003,
        http_status=403,
        message="You don't have access to this label.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrInvalidPermission": ErrorCodeSpec(
        name="models.ErrInvalidPermission",
        const="ErrCodeInvalidRight",
        error="ErrInvalidPermission",
        code=9001,
        http_status=400,
        message="The permission is invalid.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrBucketDoesNotExist": ErrorCodeSpec(
        name="models.ErrBucketDoesNotExist",
        const="ErrCodeBucketDoesNotExist",
        error="ErrBucketDoesNotExist",
        code=10001,
        http_status=404,
        message="This bucket does not exist.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrBucketDoesNotBelongToProjectView": ErrorCodeSpec(
        name="models.ErrBucketDoesNotBelongToProjectView",
        const="ErrCodeBucketDoesNotBelongToProject",
        error="ErrBucketDoesNotBelongToProjectView",
        code=10002,
        http_status=400,
        message="This bucket does not belong to that project.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrCannotRemoveLastBucket": ErrorCodeSpec(
        name="models.ErrCannotRemoveLastBucket",
        const="ErrCodeCannotRemoveLastBucket",
        error="ErrCannotRemoveLastBucket",
        code=10003,
        http_status=412,
        message="You cannot remove the last bucket on this project view.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrBucketLimitExceeded": ErrorCodeSpec(
        name="models.ErrBucketLimitExceeded",
        const="ErrCodeBucketLimitExceeded",
        error="ErrBucketLimitExceeded",
        code=10004,
        http_status=412,
        message="You cannot add the task to this bucket as it already exceeded the limit of tasks it can hold.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrOnlyOneDoneBucketPerProject": ErrorCodeSpec(
        name="models.ErrOnlyOneDoneBucketPerProject",
        const="ErrCodeOnlyOneDoneBucketPerProject",
        error="ErrOnlyOneDoneBucketPerProject",
        code=10005,
        http_status=412,
        message="There can be only one done bucket per project.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrTaskAlreadyExistsInBucket": ErrorCodeSpec(
        name="models.ErrTaskAlreadyExistsInBucket",
        const="ErrCodeTaskAlreadyExistsInBucket",
        error="ErrTaskAlreadyExistsInBucket",
        code=10006,
        http_status=400,
        message="This task already exists in a bucket for this project view.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrSavedFilterDoesNotExist": ErrorCodeSpec(
        name="models.ErrSavedFilterDoesNotExist",
        const="ErrCodeSavedFilterDoesNotExist",
        error="ErrSavedFilterDoesNotExist",
        code=11001,
        http_status=404,
        message="This saved filter does not exist.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrSavedFilterNotAvailableForLinkShare": ErrorCodeSpec(
        name="models.ErrSavedFilterNotAvailableForLinkShare",
        const="ErrCodeSavedFilterNotAvailableForLinkShare",
        error="ErrSavedFilterNotAvailableForLinkShare",
        code=11002,
        http_status=412,
        message="Saved filters are not available for link shares.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrUnknownSubscriptionEntityType": ErrorCodeSpec(
        name="models.ErrUnknownSubscriptionEntityType",
        const="ErrCodeUnknownSubscriptionEntityType",
        error="ErrUnknownSubscriptionEntityType",
        code=12001,
        http_status=412,
        message="The subscription entity type is invalid.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrSubscriptionAlreadyExists": ErrorCodeSpec(
        name="models.ErrSubscriptionAlreadyExists",
        const="ErrCodeSubscriptionAlreadyExists",
        error="ErrSubscriptionAlreadyExists",
        code=12002,
        http_status=412,
        message="You're already subscribed.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrMustProvideUser": ErrorCodeSpec(
        name="models.ErrMustProvideUser",
        const="ErrCodeMustProvideUser",
        error="ErrMustProvideUser",
        code=12003,
        http_status=412,
        message="You must provide a user to fetch subscriptions",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrLinkSharePasswordRequired": ErrorCodeSpec(
        name="models.ErrLinkSharePasswordRequired",
        const="ErrCodeLinkSharePasswordRequired",
        error="ErrLinkSharePasswordRequired",
        code=13001,
        http_status=412,
        message="This link share requires a password for authentication, but none was provided.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrLinkSharePasswordInvalid": ErrorCodeSpec(
        name="models.ErrLinkSharePasswordInvalid",
        const="ErrCodeLinkSharePasswordInvalid",
        error="ErrLinkSharePasswordInvalid",
        code=13002,
        http_status=403,
        message="The provided link share password is invalid.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrLinkShareTokenInvalid": ErrorCodeSpec(
        name="models.ErrLinkShareTokenInvalid",
        const="ErrCodeLinkShareTokenInvalid",
        error="ErrLinkShareTokenInvalid",
        code=13003,
        http_status=400,
        message="The provided link share token is invalid.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrAPITokenInvalid": ErrorCodeSpec(
        name="models.ErrAPITokenInvalid",
        const="ErrCodeAPITokenInvalid",
        error="ErrAPITokenInvalid",
        code=14001,
        http_status=400,
        message="The provided api token is invalid.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrInvalidAPITokenPermission": ErrorCodeSpec(
        name="models.ErrInvalidAPITokenPermission",
        const="ErrCodeInvalidAPITokenPermission",
        error="ErrInvalidAPITokenPermission",
        code=14002,
        http_status=400,
        message="The permission {permission} of group {group} is invalid.",
        template_fields=("permission", "group"),
        i18n_params=(("permission", "permission"), ("group", "group")),
        source="models",
    ),
    "models.ErrOpenIDBadRequest": ErrorCodeSpec(
        name="models.ErrOpenIDBadRequest",
        const="ErrCodeOpenIDError",
        error="ErrOpenIDBadRequest",
        code=15001,
        http_status=400,
        message="{message}",
        template_fields=("message",),
        i18n_params=(),
        source="models",
    ),
    "models.ErrSessionNotFound": ErrorCodeSpec(
        name="models.ErrSessionNotFound",
        const="ErrCodeSessionNotFound",
        error="ErrSessionNotFound",
        code=16001,
        http_status=404,
        message="The session does not exist.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrOAuthClientNotFound": ErrorCodeSpec(
        name="models.ErrOAuthClientNotFound",
        const="ErrCodeOAuthClientNotFound",
        error="ErrOAuthClientNotFound",
        code=17001,
        http_status=400,
        message="The OAuth client ID is not recognized.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrOAuthInvalidRedirectURI": ErrorCodeSpec(
        name="models.ErrOAuthInvalidRedirectURI",
        const="ErrCodeOAuthInvalidRedirectURI",
        error="ErrOAuthInvalidRedirectURI",
        code=17002,
        http_status=400,
        message="The redirect URI is not allowed for this client.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrOAuthMissingPKCE": ErrorCodeSpec(
        name="models.ErrOAuthMissingPKCE",
        const="ErrCodeOAuthMissingPKCE",
        error="ErrOAuthMissingPKCE",
        code=17003,
        http_status=400,
        message="PKCE (code_challenge with S256 method) is required.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrOAuthCodeInvalid": ErrorCodeSpec(
        name="models.ErrOAuthCodeInvalid",
        const="ErrCodeOAuthCodeInvalid",
        error="ErrOAuthCodeInvalid",
        code=17004,
        http_status=400,
        message="The authorization code is invalid or has already been used.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrOAuthCodeExpired": ErrorCodeSpec(
        name="models.ErrOAuthCodeExpired",
        const="ErrCodeOAuthCodeExpired",
        error="ErrOAuthCodeExpired",
        code=17005,
        http_status=400,
        message="The authorization code has expired.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrOAuthPKCEVerifyFailed": ErrorCodeSpec(
        name="models.ErrOAuthPKCEVerifyFailed",
        const="ErrCodeOAuthPKCEVerifyFailed",
        error="ErrOAuthPKCEVerifyFailed",
        code=17006,
        http_status=400,
        message="The code_verifier does not match the code_challenge.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrOAuthInvalidGrantType": ErrorCodeSpec(
        name="models.ErrOAuthInvalidGrantType",
        const="ErrCodeOAuthInvalidGrantType",
        error="ErrOAuthInvalidGrantType",
        code=17007,
        http_status=400,
        message="The grant_type is not supported. Use 'authorization_code' or 'refresh_token'.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrTimeEntryDoesNotExist": ErrorCodeSpec(
        name="models.ErrTimeEntryDoesNotExist",
        const="ErrCodeTimeEntryDoesNotExist",
        error="ErrTimeEntryDoesNotExist",
        code=18001,
        http_status=404,
        message="This time entry does not exist.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrTimeEntryInvalidContainer": ErrorCodeSpec(
        name="models.ErrTimeEntryInvalidContainer",
        const="ErrCodeTimeEntryInvalidContainer",
        error="ErrTimeEntryInvalidContainer",
        code=18002,
        http_status=400,
        message="A time entry must be attached to exactly one of a task or a project.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrInvalidTimeEntryFilterField": ErrorCodeSpec(
        name="models.ErrInvalidTimeEntryFilterField",
        const="ErrCodeInvalidTimeEntryFilterField",
        error="ErrInvalidTimeEntryFilterField",
        code=18003,
        http_status=400,
        message="The time entry filter field '{field}' is invalid. Filterable fields are user_id, task_id, project_id, start_time and end_time.",
        template_fields=("field",),
        i18n_params=(),
        source="models",
    ),
    "models.ErrInvalidTimeEntryFilterValue": ErrorCodeSpec(
        name="models.ErrInvalidTimeEntryFilterValue",
        const="ErrCodeInvalidTimeEntryFilterValue",
        error="ErrInvalidTimeEntryFilterValue",
        code=18004,
        http_status=400,
        message="The value '{value}' is not valid for the time entry filter field '{field}'.",
        template_fields=("value", "field"),
        i18n_params=(),
        source="models",
    ),
    "models.ErrNoRunningTimer": ErrorCodeSpec(
        name="models.ErrNoRunningTimer",
        const="ErrCodeNoRunningTimer",
        error="ErrNoRunningTimer",
        code=18005,
        http_status=404,
        message="You do not have a running timer.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrTimeEntryAlreadyEnded": ErrorCodeSpec(
        name="models.ErrTimeEntryAlreadyEnded",
        const="ErrCodeTimeEntryAlreadyEnded",
        error="ErrTimeEntryAlreadyEnded",
        code=18006,
        http_status=400,
        message="A time entry that has already ended cannot be reopened into a running timer. Start a new timer instead.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrTimeEntryEndBeforeStart": ErrorCodeSpec(
        name="models.ErrTimeEntryEndBeforeStart",
        const="ErrCodeTimeEntryEndBeforeStart",
        error="ErrTimeEntryEndBeforeStart",
        code=18007,
        http_status=400,
        message="A time entry's end time cannot be before its start time.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "models.ErrUserDataExportDoesNotExist": ErrorCodeSpec(
        name="models.ErrUserDataExportDoesNotExist",
        const="ErrCodeUserDataExportDoesNotExist",
        error="ErrUserDataExportDoesNotExist",
        code=19001,
        http_status=404,
        message="No user data export found.",
        template_fields=(),
        i18n_params=(),
        source="models",
    ),
    "user.ErrUsernameExists": ErrorCodeSpec(
        name="user.ErrUsernameExists",
        const="ErrorCodeUsernameExists",
        error="ErrUsernameExists",
        code=1001,
        http_status=400,
        message="A user with this username already exists.",
        template_fields=(),
        i18n_params=(),
        source="user",
    ),
    "user.ErrUserEmailExists": ErrorCodeSpec(
        name="user.ErrUserEmailExists",
        const="ErrorCodeUserEmailExists",
        error="ErrUserEmailExists",
        code=1002,
        http_status=400,
        message="A user with this email address already exists.",
        template_fields=(),
        i18n_params=(),
        source="user",
    ),
    "user.ErrNoUsernamePassword": ErrorCodeSpec(
        name="user.ErrNoUsernamePassword",
        const="ErrCodeNoUsernamePassword",
        error="ErrNoUsernamePassword",
        code=1004,
        http_status=400,
        message="Please specify a username and a password.",
        template_fields=(),
        i18n_params=(),
        source="user",
    ),
    "user.ErrUserDoesNotExist": ErrorCodeSpec(
        name="user.ErrUserDoesNotExist",
        const="ErrCodeUserDoesNotExist",
        error="ErrUserDoesNotExist",
        code=1005,
        http_status=404,
        message="The user does not exist.",
        template_fields=(),
        i18n_params=(),
        source="user",
    ),
    "user.ErrCouldNotGetUserID": ErrorCodeSpec(
        name="user.ErrCouldNotGetUserID",
        const="ErrCodeCouldNotGetUserID",
        error="ErrCouldNotGetUserID",
        code=1006,
        http_status=400,
        message="Could not get user id.",
        template_fields=(),
        i18n_params=(),
        source="user",
    ),
    "user.ErrNoPasswordResetToken": ErrorCodeSpec(
        name="user.ErrNoPasswordResetToken",
        const="ErrCodeNoPasswordResetToken",
        error="ErrNoPasswordResetToken",
        code=1008,
        http_status=412,
        message="No token to reset a user's password provided.",
        template_fields=(),
        i18n_params=(),
        source="user",
    ),
    "user.ErrInvalidPasswordResetToken": ErrorCodeSpec(
        name="user.ErrInvalidPasswordResetToken",
        const="ErrCodeInvalidPasswordResetToken",
        error="ErrInvalidPasswordResetToken",
        code=1009,
        http_status=412,
        message="Invalid token to reset a user's password.",
        template_fields=(),
        i18n_params=(),
        source="user",
    ),
    "user.ErrInvalidEmailConfirmToken": ErrorCodeSpec(
        name="user.ErrInvalidEmailConfirmToken",
        const="ErrCodeInvalidEmailConfirmToken",
        error="ErrInvalidEmailConfirmToken",
        code=1010,
        http_status=412,
        message="Invalid email confirm token.",
        template_fields=(),
        i18n_params=(),
        source="user",
    ),
    "user.ErrWrongUsernameOrPassword": ErrorCodeSpec(
        name="user.ErrWrongUsernameOrPassword",
        const="ErrCodeWrongUsernameOrPassword",
        error="ErrWrongUsernameOrPassword",
        code=1011,
        http_status=403,
        message="Wrong username or password.",
        template_fields=(),
        i18n_params=(),
        source="user",
    ),
    "user.ErrEmailNotConfirmed": ErrorCodeSpec(
        name="user.ErrEmailNotConfirmed",
        const="ErrCodeEmailNotConfirmed",
        error="ErrEmailNotConfirmed",
        code=1012,
        http_status=412,
        message="Please confirm your email address.",
        template_fields=(),
        i18n_params=(),
        source="user",
    ),
    "user.ErrEmptyNewPassword": ErrorCodeSpec(
        name="user.ErrEmptyNewPassword",
        const="ErrCodeEmptyNewPassword",
        error="ErrEmptyNewPassword",
        code=1013,
        http_status=412,
        message="Please specify new password.",
        template_fields=(),
        i18n_params=(),
        source="user",
    ),
    "user.ErrEmptyOldPassword": ErrorCodeSpec(
        name="user.ErrEmptyOldPassword",
        const="ErrCodeEmptyOldPassword",
        error="ErrEmptyOldPassword",
        code=1014,
        http_status=412,
        message="Please specify old password.",
        template_fields=(),
        i18n_params=(),
        source="user",
    ),
    "user.ErrTOTPAlreadyEnabled": ErrorCodeSpec(
        name="user.ErrTOTPAlreadyEnabled",
        const="ErrCodeTOTPAlreadyEnabled",
        error="ErrTOTPAlreadyEnabled",
        code=1015,
        http_status=412,
        message="Totp is already enabled for this user, but not activated.",
        template_fields=(),
        i18n_params=(),
        source="user",
    ),
    "user.ErrTOTPNotEnabled": ErrorCodeSpec(
        name="user.ErrTOTPNotEnabled",
        const="ErrCodeTOTPNotEnabled",
        error="ErrTOTPNotEnabled",
        code=1016,
        http_status=412,
        message="Totp is not enabled for this user.",
        template_fields=(),
        i18n_params=(),
        source="user",
    ),
    "user.ErrInvalidTOTPPasscode": ErrorCodeSpec(
        name="user.ErrInvalidTOTPPasscode",
        const="ErrCodeInvalidTOTPPasscode",
        error="ErrInvalidTOTPPasscode",
        code=1017,
        http_status=412,
        message="Invalid totp passcode.",
        template_fields=(),
        i18n_params=(),
        source="user",
    ),
    "user.ErrTOTPPasscodeUsed": ErrorCodeSpec(
        name="user.ErrTOTPPasscodeUsed",
        const="ErrCodeTOTPPasscodeUsed",
        error="ErrTOTPPasscodeUsed",
        code=1025,
        http_status=412,
        message="This totp passcode has already been used.",
        template_fields=(),
        i18n_params=(),
        source="user",
    ),
    "user.ErrInvalidAvatarProvider": ErrorCodeSpec(
        name="user.ErrInvalidAvatarProvider",
        const="ErrCodeInvalidAvatarProvider",
        error="ErrInvalidAvatarProvider",
        code=1018,
        http_status=412,
        message="Invalid avatar provider setting. See docs for valid types.",
        template_fields=(),
        i18n_params=(),
        source="user",
    ),
    "user.ErrNoOpenIDEmailProvided": ErrorCodeSpec(
        name="user.ErrNoOpenIDEmailProvided",
        const="ErrCodeNoOpenIDEmailProvided",
        error="ErrNoOpenIDEmailProvided",
        code=1019,
        http_status=412,
        message="No email address available. Please make sure the openid provider publicly provides an email address for your account.",
        template_fields=(),
        i18n_params=(),
        source="user",
    ),
    "user.ErrOpenIDCustomScopeMalformed": ErrorCodeSpec(
        name="user.ErrOpenIDCustomScopeMalformed",
        const="ErrCodeOpenIDCustomScopeMalformed",
        error="ErrOpenIDCustomScopeMalformed",
        code=1022,
        http_status=412,
        message="The custom scope set by the OIDC provider is malformed. Please make sure the openid provider sets the data correctly for your scope. Check especially to have set an oidcID",
        template_fields=(),
        i18n_params=(),
        source="user",
    ),
    "user.ErrAccountDisabled": ErrorCodeSpec(
        name="user.ErrAccountDisabled",
        const="ErrCodeAccountDisabled",
        error="ErrAccountDisabled",
        code=1020,
        http_status=412,
        message="This account is disabled. Check your emails or ask your administrator.",
        template_fields=(),
        i18n_params=(),
        source="user",
    ),
    "user.ErrAccountLocked": ErrorCodeSpec(
        name="user.ErrAccountLocked",
        const="ErrCodeAccountLocked",
        error="ErrAccountLocked",
        code=1026,
        http_status=412,
        message="This account is locked due to too many failed login attempts. You can reset your password to unlock it.",
        template_fields=(),
        i18n_params=(),
        source="user",
    ),
    "user.ErrAccountIsNotLocal": ErrorCodeSpec(
        name="user.ErrAccountIsNotLocal",
        const="ErrCodeAccountIsNotLocal",
        error="ErrAccountIsNotLocal",
        code=1021,
        http_status=412,
        message="This account is managed by a third-party authentication provider.",
        template_fields=(),
        i18n_params=(),
        source="user",
    ),
    "user.ErrUsernameMustNotContainSpaces": ErrorCodeSpec(
        name="user.ErrUsernameMustNotContainSpaces",
        const="ErrCodeUsernameMustNotContainSpaces",
        error="ErrUsernameMustNotContainSpaces",
        code=1022,
        http_status=412,
        message="The username must not contain spaces.",
        template_fields=(),
        i18n_params=(),
        source="user",
    ),
    "user.ErrMustNotBeLinkShare": ErrorCodeSpec(
        name="user.ErrMustNotBeLinkShare",
        const="ErrCodeMustNotBeLinkShare",
        error="ErrMustNotBeLinkShare",
        code=1023,
        http_status=403,
        message="You can't do that as a link share.",
        template_fields=(),
        i18n_params=(),
        source="user",
    ),
    "user.ErrInvalidClaimData": ErrorCodeSpec(
        name="user.ErrInvalidClaimData",
        const="ErrCodeInvalidClaimData",
        error="ErrInvalidClaimData",
        code=1024,
        http_status=400,
        message="Invalid claim data for field {field} of type {type}",
        template_fields=("field", "type"),
        i18n_params=(("field", "field"), ("type", "type")),
        source="user",
    ),
    "user.ErrInvalidTimezone": ErrorCodeSpec(
        name="user.ErrInvalidTimezone",
        const="ErrorCodeInvalidTimezone",
        error="ErrInvalidTimezone",
        code=1025,
        http_status=400,
        message="The timezone '{name}' is invalid. Please select a valid timezone from the list.",
        template_fields=("name",),
        i18n_params=(("timezone", "name"),),
        source="user",
    ),
    "user.ErrUsernameReserved": ErrorCodeSpec(
        name="user.ErrUsernameReserved",
        const="ErrorCodeUsernameReserved",
        error="ErrUsernameReserved",
        code=1026,
        http_status=400,
        message="This username is reserved and cannot be used.",
        template_fields=(),
        i18n_params=(),
        source="user",
    ),
    "user.ErrInvalidUserContext": ErrorCodeSpec(
        name="user.ErrInvalidUserContext",
        const="ErrorCodeInvalidUserContext",
        error="ErrInvalidUserContext",
        code=1027,
        http_status=401,
        message="Invalid user context. Please make sure the passed token is valid and try again.",
        template_fields=(),
        i18n_params=(),
        source="user",
    ),
    "user.ErrInvalidDeletionToken": ErrorCodeSpec(
        name="user.ErrInvalidDeletionToken",
        const="ErrorCodeInvalidDeletionToken",
        error="ErrInvalidDeletionToken",
        code=1028,
        http_status=400,
        message="Invalid deletion token provided.",
        template_fields=(),
        i18n_params=(),
        source="user",
    ),
    "user.ErrTokenUserMismatch": ErrorCodeSpec(
        name="user.ErrTokenUserMismatch",
        const="ErrorCodeTokenUserMismatch",
        error="ErrTokenUserMismatch",
        code=1029,
        http_status=403,
        message="This deletion token does not belong to your account.",
        template_fields=(),
        i18n_params=(),
        source="user",
    ),
    "user.ErrLastAdmin": ErrorCodeSpec(
        name="user.ErrLastAdmin",
        const="ErrCodeLastAdmin",
        error="ErrLastAdmin",
        code=1030,
        http_status=400,
        message="Cannot remove the last remaining instance admin.",
        template_fields=(),
        i18n_params=(),
        source="user",
    ),
    "user.ErrAccountIsBot": ErrorCodeSpec(
        name="user.ErrAccountIsBot",
        const="ErrCodeAccountIsBot",
        error="ErrAccountIsBot",
        code=1031,
        http_status=412,
        message="This account is a bot and cannot log in interactively.",
        template_fields=(),
        i18n_params=(),
        source="user",
    ),
    "user.ErrBotNotOwned": ErrorCodeSpec(
        name="user.ErrBotNotOwned",
        const="ErrCodeBotNotOwned",
        error="ErrBotNotOwned",
        code=1033,
        http_status=403,
        message="You do not own this bot user.",
        template_fields=(),
        i18n_params=(),
        source="user",
    ),
    "user.ErrBotUsernameMustHavePrefix": ErrorCodeSpec(
        name="user.ErrBotUsernameMustHavePrefix",
        const="ErrCodeBotUsernameMustHavePrefix",
        error="ErrBotUsernameMustHavePrefix",
        code=1034,
        http_status=400,
        message="Bot usernames must start with the 'bot-' prefix.",
        template_fields=(),
        i18n_params=(),
        source="user",
    ),
}


def spec_for_value(code: int) -> ErrorCodeSpec:
    """Look an error up by its numeric code.

    Raises AmbiguousErrorCodeError for the three values upstream reuses. Prefer
    keying by constant name; this exists for decoding responses, not raising.
    """
    matches = [spec for spec in ERROR_CODES.values() if spec.code == code]
    if not matches:
        raise LookupError(f"no error code {code}")
    if len(matches) > 1:
        names = ", ".join(sorted(spec.name for spec in matches))
        raise AmbiguousErrorCodeError(f"code {code} maps to several errors: {names}")
    return matches[0]
