"""Baseline schema — all 24 Phase 1 tables.

Calton does not reproduce upstream's 60-plus historical xorm migrations; it starts from
one migration shaped like the current schema (design §1.3). Column names, types, order,
defaults and index names are matched to what the Go binary builds — see
``tests/unit/test_schema_parity.py``, which runs this migration and diffs the result
against ``tests/fixtures/go_schema.json``.

Revision ID: 0001
Revises:
Create Date: 2026-08-03
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import calton.db.types

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_tokens",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("token_salt", sa.Text(), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("token_last_eight", sa.Text(), nullable=False),
        sa.Column("permissions", sa.Text(), nullable=False),
        sa.Column("expires_at", calton.db.types.CaltonDateTime(), nullable=False),
        sa.Column("created", calton.db.types.CaltonDateTime(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("PK_api_tokens")),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("api_tokens", schema=None) as batch_op:
        batch_op.create_index("IDX_api_tokens_token_last_eight", ["token_last_eight"], unique=False)
        batch_op.create_index("UQE_api_tokens_id", ["id"], unique=True)
        batch_op.create_index("UQE_api_tokens_token_hash", ["token_hash"], unique=True)

    op.create_table(
        "buckets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("project_view_id", sa.Integer(), nullable=False),
        sa.Column("limit", sa.Integer(), server_default=sa.text("0"), nullable=True),
        sa.Column("position", sa.REAL(), nullable=True),
        sa.Column("created", calton.db.types.CaltonDateTime(), nullable=False),
        sa.Column("updated", calton.db.types.CaltonDateTime(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("PK_buckets")),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("buckets", schema=None) as batch_op:
        batch_op.create_index("UQE_buckets_id", ["id"], unique=True)

    op.create_table(
        "favorites",
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("entity_id", "user_id", "kind", name=op.f("PK_favorites")),
    )
    op.create_table(
        "files",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("mime", sa.Text(), nullable=True),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("created", calton.db.types.CaltonDateTime(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("PK_files")),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.create_index("UQE_files_id", ["id"], unique=True)

    op.create_table(
        "label_tasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("label_id", sa.Integer(), nullable=False),
        sa.Column("created", calton.db.types.CaltonDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("PK_label_tasks")),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("label_tasks", schema=None) as batch_op:
        batch_op.create_index("IDX_label_tasks_label_id", ["label_id"], unique=False)
        batch_op.create_index("IDX_label_tasks_task_id", ["task_id"], unique=False)
        batch_op.create_index("UQE_label_tasks_id", ["id"], unique=True)

    op.create_table(
        "labels",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("hex_color", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("created", calton.db.types.CaltonDateTime(), nullable=False),
        sa.Column("updated", calton.db.types.CaltonDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("PK_labels")),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("labels", schema=None) as batch_op:
        batch_op.create_index("UQE_labels_id", ["id"], unique=True)

    op.create_table(
        "project_views",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("view_kind", sa.Integer(), nullable=False),
        sa.Column("filter", sa.Text(), server_default=sa.text("(null)"), nullable=True),
        sa.Column("position", sa.REAL(), nullable=True),
        sa.Column(
            "bucket_configuration_mode", sa.Integer(), server_default=sa.text("0"), nullable=True
        ),
        sa.Column("bucket_configuration", sa.Text(), nullable=True),
        sa.Column("default_bucket_id", sa.Integer(), nullable=True),
        sa.Column("done_bucket_id", sa.Integer(), nullable=True),
        sa.Column("updated", calton.db.types.CaltonDateTime(), nullable=False),
        sa.Column("created", calton.db.types.CaltonDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("PK_project_views")),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("project_views", schema=None) as batch_op:
        batch_op.create_index(
            "IDX_project_views_default_bucket_id", ["default_bucket_id"], unique=False
        )
        batch_op.create_index("IDX_project_views_done_bucket_id", ["done_bucket_id"], unique=False)
        batch_op.create_index("IDX_project_views_project_id", ["project_id"], unique=False)
        batch_op.create_index("UQE_project_views_id", ["id"], unique=True)

    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("identifier", sa.Text(), nullable=True),
        sa.Column("hex_color", sa.Text(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("parent_project_id", sa.Integer(), nullable=True),
        sa.Column(
            "is_archived",
            calton.db.types.CaltonBoolean(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("background_file_id", sa.Integer(), nullable=True),
        sa.Column("background_blur_hash", sa.Text(), nullable=True),
        sa.Column("position", sa.REAL(), nullable=True),
        sa.Column("created", calton.db.types.CaltonDateTime(), nullable=False),
        sa.Column("updated", calton.db.types.CaltonDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("PK_projects")),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.create_index("IDX_projects_owner_id", ["owner_id"], unique=False)
        batch_op.create_index("IDX_projects_parent_project_id", ["parent_project_id"], unique=False)
        batch_op.create_index("UQE_projects_id", ["id"], unique=True)

    op.create_table(
        "saved_filters",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("filters", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column(
            "is_favorite",
            calton.db.types.CaltonBoolean(),
            server_default=sa.text("0"),
            nullable=True,
        ),
        sa.Column("created", calton.db.types.CaltonDateTime(), nullable=False),
        sa.Column("updated", calton.db.types.CaltonDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("PK_saved_filters")),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("saved_filters", schema=None) as batch_op:
        batch_op.create_index("IDX_saved_filters_owner_id", ["owner_id"], unique=False)
        batch_op.create_index("UQE_saved_filters_id", ["id"], unique=True)

    op.create_table(
        "subscriptions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("entity_type", sa.Integer(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created", calton.db.types.CaltonDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("PK_subscriptions")),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.create_index("IDX_subscriptions_entity_id", ["entity_id"], unique=False)
        batch_op.create_index("IDX_subscriptions_entity_type", ["entity_type"], unique=False)
        batch_op.create_index("IDX_subscriptions_user_id", ["user_id"], unique=False)
        batch_op.create_index("UQE_subscriptions_id", ["id"], unique=True)

    op.create_table(
        "task_assignees",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created", calton.db.types.CaltonDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("PK_task_assignees")),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("task_assignees", schema=None) as batch_op:
        batch_op.create_index("IDX_task_assignees_task_id", ["task_id"], unique=False)
        batch_op.create_index("IDX_task_assignees_user_id", ["user_id"], unique=False)
        batch_op.create_index("UQE_task_assignees_id", ["id"], unique=True)

    op.create_table(
        "task_attachments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("created", calton.db.types.CaltonDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("PK_task_attachments")),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("task_attachments", schema=None) as batch_op:
        batch_op.create_index("UQE_task_attachments_id", ["id"], unique=True)

    op.create_table(
        "task_buckets",
        sa.Column("bucket_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("project_view_id", sa.Integer(), nullable=False),
    )
    with op.batch_alter_table("task_buckets", schema=None) as batch_op:
        batch_op.create_index("IDX_task_buckets_bucket_id", ["bucket_id"], unique=False)
        batch_op.create_index("IDX_task_buckets_project_view_id", ["project_view_id"], unique=False)
        batch_op.create_index("IDX_task_buckets_task_id", ["task_id"], unique=False)
        batch_op.create_index(
            "UQE_task_buckets_task_view", ["task_id", "project_view_id"], unique=True
        )

    op.create_table(
        "task_comments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("created", calton.db.types.CaltonDateTime(), nullable=True),
        sa.Column("updated", calton.db.types.CaltonDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("PK_task_comments")),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("task_comments", schema=None) as batch_op:
        batch_op.create_index("IDX_task_comments_task_id", ["task_id"], unique=False)
        batch_op.create_index("UQE_task_comments_id", ["id"], unique=True)

    op.create_table(
        "task_positions",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("project_view_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.REAL(), nullable=False),
    )
    with op.batch_alter_table("task_positions", schema=None) as batch_op:
        batch_op.create_index(
            "IDX_task_positions_project_view_id", ["project_view_id"], unique=False
        )
        batch_op.create_index("IDX_task_positions_task_id", ["task_id"], unique=False)
        batch_op.create_index(
            "IDX_task_positions_view_position", ["project_view_id", "position"], unique=False
        )
        batch_op.create_index(
            "UQE_task_positions_task_view", ["task_id", "project_view_id"], unique=True
        )

    op.create_table(
        "task_relations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("other_task_id", sa.Integer(), nullable=False),
        sa.Column("relation_kind", sa.Text(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("created", calton.db.types.CaltonDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("PK_task_relations")),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("task_relations", schema=None) as batch_op:
        batch_op.create_index("UQE_task_relations_id", ["id"], unique=True)

    op.create_table(
        "task_reminders",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("reminder", calton.db.types.CaltonDateTime(), nullable=False),
        sa.Column("created", calton.db.types.CaltonDateTime(), nullable=False),
        sa.Column("relative_period", sa.Integer(), nullable=True),
        sa.Column("relative_to", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("PK_task_reminders")),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("task_reminders", schema=None) as batch_op:
        batch_op.create_index("IDX_task_reminders_reminder", ["reminder"], unique=False)
        batch_op.create_index("IDX_task_reminders_task_id", ["task_id"], unique=False)
        batch_op.create_index("UQE_task_reminders_id", ["id"], unique=True)

    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("done", calton.db.types.CaltonBoolean(), nullable=True),
        sa.Column("done_at", calton.db.types.CaltonDateTime(), nullable=True),
        sa.Column("due_date", calton.db.types.CaltonDateTime(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("repeat_after", sa.Integer(), nullable=True),
        sa.Column("repeat_mode", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("start_date", calton.db.types.CaltonDateTime(), nullable=True),
        sa.Column("end_date", calton.db.types.CaltonDateTime(), nullable=True),
        sa.Column("hex_color", sa.Text(), nullable=True),
        sa.Column("percent_done", sa.REAL(), nullable=True),
        sa.Column("index", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("uid", sa.Text(), nullable=True),
        sa.Column(
            "cover_image_attachment_id", sa.Integer(), server_default=sa.text("0"), nullable=True
        ),
        sa.Column("created", calton.db.types.CaltonDateTime(), nullable=False),
        sa.Column("updated", calton.db.types.CaltonDateTime(), nullable=False),
        sa.Column("deleted_at", calton.db.types.CaltonDateTime(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("PK_tasks")),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("IDX_tasks_deleted_at"), ["deleted_at"], unique=False)
        batch_op.create_index("IDX_tasks_done", ["done"], unique=False)
        batch_op.create_index("IDX_tasks_done_at", ["done_at"], unique=False)
        batch_op.create_index("IDX_tasks_due_date", ["due_date"], unique=False)
        batch_op.create_index("IDX_tasks_end_date", ["end_date"], unique=False)
        batch_op.create_index("IDX_tasks_project_id", ["project_id"], unique=False)
        batch_op.create_index("IDX_tasks_repeat_after", ["repeat_after"], unique=False)
        batch_op.create_index("IDX_tasks_start_date", ["start_date"], unique=False)
        batch_op.create_index("UQE_tasks_id", ["id"], unique=True)
        batch_op.create_index("UQE_tasks_tasks_project_index", ["project_id", "index"], unique=True)

    op.create_table(
        "team_members",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("admin", calton.db.types.CaltonBoolean(), nullable=True),
        sa.Column("created", calton.db.types.CaltonDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("PK_team_members")),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("team_members", schema=None) as batch_op:
        batch_op.create_index("IDX_team_members_team_id", ["team_id"], unique=False)
        batch_op.create_index("IDX_team_members_user_id", ["user_id"], unique=False)
        batch_op.create_index("UQE_team_members_id", ["id"], unique=True)

    op.create_table(
        "team_projects",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("permission", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("created", calton.db.types.CaltonDateTime(), nullable=False),
        sa.Column("updated", calton.db.types.CaltonDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("PK_team_projects")),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("team_projects", schema=None) as batch_op:
        batch_op.create_index("IDX_team_projects_permission", ["permission"], unique=False)
        batch_op.create_index("IDX_team_projects_project_id", ["project_id"], unique=False)
        batch_op.create_index("IDX_team_projects_team_id", ["team_id"], unique=False)
        batch_op.create_index("UQE_team_projects_id", ["id"], unique=True)

    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=True),
        sa.Column("issuer", sa.Text(), nullable=True),
        sa.Column("created", calton.db.types.CaltonDateTime(), nullable=True),
        sa.Column("updated", calton.db.types.CaltonDateTime(), nullable=True),
        sa.Column(
            "is_public",
            calton.db.types.CaltonBoolean(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("PK_teams")),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.create_index("IDX_teams_created_by_id", ["created_by_id"], unique=False)
        batch_op.create_index("UQE_teams_id", ["id"], unique=True)

    op.create_table(
        "user_tokens",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.Text(), nullable=False),
        sa.Column("kind", sa.Integer(), nullable=False),
        sa.Column("created", calton.db.types.CaltonDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("PK_user_tokens")),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("user_tokens", schema=None) as batch_op:
        batch_op.create_index("IDX_user_tokens_token", ["token"], unique=False)
        batch_op.create_index("UQE_user_tokens_id", ["id"], unique=True)

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("password", sa.Text(), nullable=True),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("status", sa.Integer(), server_default=sa.text("0"), nullable=True),
        sa.Column(
            "is_admin",
            calton.db.types.CaltonBoolean(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("avatar_provider", sa.Text(), nullable=True),
        sa.Column("avatar_file_id", sa.Integer(), nullable=True),
        sa.Column("issuer", sa.Text(), nullable=True),
        sa.Column("subject", sa.Text(), nullable=True),
        sa.Column(
            "email_reminders_enabled",
            calton.db.types.CaltonBoolean(),
            server_default=sa.text("1"),
            nullable=True,
        ),
        sa.Column(
            "discoverable_by_name",
            calton.db.types.CaltonBoolean(),
            server_default=sa.text("0"),
            nullable=True,
        ),
        sa.Column(
            "discoverable_by_email",
            calton.db.types.CaltonBoolean(),
            server_default=sa.text("0"),
            nullable=True,
        ),
        sa.Column(
            "overdue_tasks_reminders_enabled",
            calton.db.types.CaltonBoolean(),
            server_default=sa.text("1"),
            nullable=True,
        ),
        sa.Column(
            "overdue_tasks_reminders_time",
            sa.Text(),
            server_default=sa.text("'09:00'"),
            nullable=False,
        ),
        sa.Column("default_project_id", sa.Integer(), nullable=True),
        sa.Column("bot_owner_id", sa.Integer(), nullable=True),
        sa.Column("week_start", sa.Integer(), nullable=True),
        sa.Column("language", sa.Text(), nullable=True),
        sa.Column("timezone", sa.Text(), nullable=True),
        sa.Column("deletion_scheduled_at", calton.db.types.CaltonDateTime(), nullable=True),
        sa.Column("deletion_last_reminder_sent", calton.db.types.CaltonDateTime(), nullable=True),
        sa.Column("frontend_settings", sa.Text(), nullable=True),
        sa.Column("extra_settings_links", sa.Text(), nullable=True),
        sa.Column("export_file_id", sa.Integer(), nullable=True),
        sa.Column("created", calton.db.types.CaltonDateTime(), nullable=False),
        sa.Column("updated", calton.db.types.CaltonDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("PK_users")),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index("IDX_users_bot_owner_id", ["bot_owner_id"], unique=False)
        batch_op.create_index("IDX_users_default_project_id", ["default_project_id"], unique=False)
        batch_op.create_index(
            "IDX_users_discoverable_by_email", ["discoverable_by_email"], unique=False
        )
        batch_op.create_index(
            "IDX_users_discoverable_by_name", ["discoverable_by_name"], unique=False
        )
        batch_op.create_index(
            "IDX_users_overdue_tasks_reminders_enabled",
            ["overdue_tasks_reminders_enabled"],
            unique=False,
        )
        batch_op.create_index("UQE_users_id", ["id"], unique=True)
        batch_op.create_index("UQE_users_username", ["username"], unique=True)

    op.create_table(
        "users_projects",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("permission", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("created", calton.db.types.CaltonDateTime(), nullable=False),
        sa.Column("updated", calton.db.types.CaltonDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("PK_users_projects")),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("users_projects", schema=None) as batch_op:
        batch_op.create_index("IDX_users_projects_permission", ["permission"], unique=False)
        batch_op.create_index("IDX_users_projects_project_id", ["project_id"], unique=False)
        batch_op.create_index("IDX_users_projects_user_id", ["user_id"], unique=False)
        batch_op.create_index("UQE_users_projects_id", ["id"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users_projects", schema=None) as batch_op:
        batch_op.drop_index("UQE_users_projects_id")
        batch_op.drop_index("IDX_users_projects_user_id")
        batch_op.drop_index("IDX_users_projects_project_id")
        batch_op.drop_index("IDX_users_projects_permission")

    op.drop_table("users_projects")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index("UQE_users_username")
        batch_op.drop_index("UQE_users_id")
        batch_op.drop_index("IDX_users_overdue_tasks_reminders_enabled")
        batch_op.drop_index("IDX_users_discoverable_by_name")
        batch_op.drop_index("IDX_users_discoverable_by_email")
        batch_op.drop_index("IDX_users_default_project_id")
        batch_op.drop_index("IDX_users_bot_owner_id")

    op.drop_table("users")
    with op.batch_alter_table("user_tokens", schema=None) as batch_op:
        batch_op.drop_index("UQE_user_tokens_id")
        batch_op.drop_index("IDX_user_tokens_token")

    op.drop_table("user_tokens")
    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.drop_index("UQE_teams_id")
        batch_op.drop_index("IDX_teams_created_by_id")

    op.drop_table("teams")
    with op.batch_alter_table("team_projects", schema=None) as batch_op:
        batch_op.drop_index("UQE_team_projects_id")
        batch_op.drop_index("IDX_team_projects_team_id")
        batch_op.drop_index("IDX_team_projects_project_id")
        batch_op.drop_index("IDX_team_projects_permission")

    op.drop_table("team_projects")
    with op.batch_alter_table("team_members", schema=None) as batch_op:
        batch_op.drop_index("UQE_team_members_id")
        batch_op.drop_index("IDX_team_members_user_id")
        batch_op.drop_index("IDX_team_members_team_id")

    op.drop_table("team_members")
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_index("UQE_tasks_tasks_project_index")
        batch_op.drop_index("UQE_tasks_id")
        batch_op.drop_index("IDX_tasks_start_date")
        batch_op.drop_index("IDX_tasks_repeat_after")
        batch_op.drop_index("IDX_tasks_project_id")
        batch_op.drop_index("IDX_tasks_end_date")
        batch_op.drop_index("IDX_tasks_due_date")
        batch_op.drop_index("IDX_tasks_done_at")
        batch_op.drop_index("IDX_tasks_done")
        batch_op.drop_index(batch_op.f("IDX_tasks_deleted_at"))

    op.drop_table("tasks")
    with op.batch_alter_table("task_reminders", schema=None) as batch_op:
        batch_op.drop_index("UQE_task_reminders_id")
        batch_op.drop_index("IDX_task_reminders_task_id")
        batch_op.drop_index("IDX_task_reminders_reminder")

    op.drop_table("task_reminders")
    with op.batch_alter_table("task_relations", schema=None) as batch_op:
        batch_op.drop_index("UQE_task_relations_id")

    op.drop_table("task_relations")
    with op.batch_alter_table("task_positions", schema=None) as batch_op:
        batch_op.drop_index("UQE_task_positions_task_view")
        batch_op.drop_index("IDX_task_positions_view_position")
        batch_op.drop_index("IDX_task_positions_task_id")
        batch_op.drop_index("IDX_task_positions_project_view_id")

    op.drop_table("task_positions")
    with op.batch_alter_table("task_comments", schema=None) as batch_op:
        batch_op.drop_index("UQE_task_comments_id")
        batch_op.drop_index("IDX_task_comments_task_id")

    op.drop_table("task_comments")
    with op.batch_alter_table("task_buckets", schema=None) as batch_op:
        batch_op.drop_index("UQE_task_buckets_task_view")
        batch_op.drop_index("IDX_task_buckets_task_id")
        batch_op.drop_index("IDX_task_buckets_project_view_id")
        batch_op.drop_index("IDX_task_buckets_bucket_id")

    op.drop_table("task_buckets")
    with op.batch_alter_table("task_attachments", schema=None) as batch_op:
        batch_op.drop_index("UQE_task_attachments_id")

    op.drop_table("task_attachments")
    with op.batch_alter_table("task_assignees", schema=None) as batch_op:
        batch_op.drop_index("UQE_task_assignees_id")
        batch_op.drop_index("IDX_task_assignees_user_id")
        batch_op.drop_index("IDX_task_assignees_task_id")

    op.drop_table("task_assignees")
    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.drop_index("UQE_subscriptions_id")
        batch_op.drop_index("IDX_subscriptions_user_id")
        batch_op.drop_index("IDX_subscriptions_entity_type")
        batch_op.drop_index("IDX_subscriptions_entity_id")

    op.drop_table("subscriptions")
    with op.batch_alter_table("saved_filters", schema=None) as batch_op:
        batch_op.drop_index("UQE_saved_filters_id")
        batch_op.drop_index("IDX_saved_filters_owner_id")

    op.drop_table("saved_filters")
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_index("UQE_projects_id")
        batch_op.drop_index("IDX_projects_parent_project_id")
        batch_op.drop_index("IDX_projects_owner_id")

    op.drop_table("projects")
    with op.batch_alter_table("project_views", schema=None) as batch_op:
        batch_op.drop_index("UQE_project_views_id")
        batch_op.drop_index("IDX_project_views_project_id")
        batch_op.drop_index("IDX_project_views_done_bucket_id")
        batch_op.drop_index("IDX_project_views_default_bucket_id")

    op.drop_table("project_views")
    with op.batch_alter_table("labels", schema=None) as batch_op:
        batch_op.drop_index("UQE_labels_id")

    op.drop_table("labels")
    with op.batch_alter_table("label_tasks", schema=None) as batch_op:
        batch_op.drop_index("UQE_label_tasks_id")
        batch_op.drop_index("IDX_label_tasks_task_id")
        batch_op.drop_index("IDX_label_tasks_label_id")

    op.drop_table("label_tasks")
    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.drop_index("UQE_files_id")

    op.drop_table("files")
    op.drop_table("favorites")
    with op.batch_alter_table("buckets", schema=None) as batch_op:
        batch_op.drop_index("UQE_buckets_id")

    op.drop_table("buckets")
    with op.batch_alter_table("api_tokens", schema=None) as batch_op:
        batch_op.drop_index("UQE_api_tokens_token_hash")
        batch_op.drop_index("UQE_api_tokens_id")
        batch_op.drop_index("IDX_api_tokens_token_last_eight")

    op.drop_table("api_tokens")
    # ### end Alembic commands ###
